foodweb/urls.py
#-*- coding: UTF-8 -*-
"""
foodweb URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required
# from django.contrib.auth.views import login, logout
# from views import index, welcome, register
# from restaurants.views import menu, list_restaurants, comment
from django.conf import settings
import django.contrib.auth.views
import views
import restaurants.views

from django.views.generic.base import TemplateView

admin.autodiscover()

urlpatterns = [
    url(r'^admin/',             include(admin.site.urls)),
    url(r'^menu/(?P<pk>\d+)/',  login_required(restaurants.views.MenuView.as_view())),
    url(r'^restaurants_list/',  login_required(restaurants.views.RestaurantsView.as_view())),
    url(r'^comment/(\d{1,5})/', login_required(restaurants.views.comment)),
    url(r'^login/',             django.contrib.auth.views.login),
    url(r'^logout/',            django.contrib.auth.views.logout),
    url(r'^accounts/login/',    django.contrib.auth.views.login),
    url(r'^accounts/logout/',   django.contrib.auth.views.logout),
    url(r'^index/',             TemplateView.as_view(template_name='index.html')),
    url(r'^welcome/',           views.welcome),
    url(r'^accounts/register/', views.register),
    url(r'^users_list/',         views.list_users),
]
# url(r'^index/',             views.index),
# url(r'index/',              views.IndexView.as_view()),
# url(r'^index/',              TemplateView().as_view(template_name='index.html')),
# url(r'^restaurants_list/',  login_required(restaurants.views.list_restaurants)),
# url(r'^menu/',              login_required(restaurants.views.menu)),
if settings.DEBUG:
    urlpatterns += [
        url(r'^test/', views.test),
    ]

restaurants/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Restaurant(models.Model):
    name = models.CharField(max_length=20)
    phone_number = models.CharField(max_length=15)
    address = models.CharField(max_length=50, blank=True)

    def __unicode__(self):
        return self.name

class Food(models.Model):
    name = models.CharField(max_length=20)
    price = models.DecimalField(max_digits=3,decimal_places=0)
    comment = models.CharField(max_length=50, blank=True)
    is_spicy = models.BooleanField(default=False)
    restaurant = models.ForeignKey(Restaurant)

    def __unicode__(self):
        return self.name

class Comment(models.Model):
    content = models.CharField(max_length=255)
    visitor = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    date_time =models.DateTimeField()
    restaurant = models.ForeignKey(Restaurant)
    class Meta:
        ordering = ['date_time']
        permissions = (
            ("can_comment", "Can comment"),
        )

restaurants/forms.py
#-*- coding: UTF-8 -*-
from django import forms

class CommentForm(forms.Form):
    visitor = forms.CharField(max_length=20)
    email = forms.EmailField(max_length=20,required=False)
    content = forms.CharField(max_length=200, widget=forms.Textarea)

    def clean_content(self):
        content = self.cleaned_data['content']
        if len(content) < 3:
            raise forms.ValidationError('字數不足，3字以上')
        return content

restaurants/views.py
#-*- coding: UTF-8 -*-
from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from restaurants.models import Restaurant,  Comment
from restaurants.forms import CommentForm
from django.utils import timezone
from django.contrib.sessions.models import Session
from django.contrib.auth.decorators import login_required, permission_required

from django.views.generic.list import ListView
from django.utils.decorators import method_decorator

from django.views.generic.detail import DetailView
from django.views.generic.edit import FormView

# Create your views here.

class MenuView(DetailView):
    model = Restaurant
    template_name = 'menu.html'
    context_object_name = 'restaurant'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(MenuView, self).dispatch(request, *args, **kwargs)

'''
def menu(request):
    if 'id' in request.GET and request.GET['id'] != '':
        restaurant = Restaurant.objects.get(id=request.GET['id'])
        return render_to_response('menu.html', locals())
    else:
        return HttpResponseRedirect("/restaurants_list")
'''

'''
方法2,3用此 method
def menu(request,id):
#    path = request.path
#   restaurants = Restaurant.objects.all()
    if id:
        restaurant = Restaurant.objects.get(id=id)
        return render_to_response('menu.html', locals())
    else:
        return HttpResponseRedirect("/restaurants_list")
'''

'''
@login_required
def list_restaurants(request):
#    if not request.user.is_authenticated():
##        return HttpResponseRedirect('/index/')
#        return HttpResponseRedirect('/accounts/login/?next={0}'.format(request.path))
    restaurants = Restaurant.objects.all()
    request.session['restaurants'] = restaurants
    return render_to_response('restaurants_list.html', locals())
'''

class RestaurantsView(ListView):
    model = Restaurant
    template_name = 'restaurants_list.html'
    context_object_name = 'restaurants'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(RestaurantsView, self).dispatch(request, *args, **kwargs)

'''
@permission_required('restaurants.can_comment',)
def comment(request, restaurant_id):

    if restaurant_id:
        r = Restaurant.objects.get(id=restaurant_id)
    else:
        return HttpResponseRedirect("/restaurants_list/")
    if request.POST:
        f = CommentForm(request.POST)
        if f.is_valid():
            visitor = request.POST['visitor']
            content = request.POST['content']
            email = request.POST['email']
            date_time = timezone.localtime(timezone.now())
            c = Comment.objects.create(
                visitor=visitor,
                email=email,
                content=content,
                date_time=date_time,
                restaurant=r
            )
            f = CommentForm(initial={'content':'很美味'})
    else:
        f = CommentForm(initial={'content':'很美味'})
    return render_to_response('comments.html',RequestContext(request, locals()))
'''

class CommentView(FormView):
    form_class = CommentForm
    template_name = 'comments.html'
    success_url = '/comment'
    initial = {'content':u'很美味'}

    def form_valid(self, form):
        Comment.objects.create(
            visitor = form.cleaned_data['visitor'],
            email = form.cleaned_data['email'],
            content = form.cleaned_data['content'],
            date_time = timezone.localtime(timezone.now()),
            restaurant = Restaurant.objects
        )





'''
自行驗證方式
    errors = []
    if request.POST:
        visitor = request.POST['visitor']
        content = request.POST['content']
        email = request.POST['email']
        date_time = timezone.localtime(timezone.now())
        if any(not request.POST[k] for k in request.POST):
            errors.append('* 有空白欄位，請不要留空')
        if '@' not in email:
            errors.append('* email格式不正確，請重新輸入')
        if not errors:
            Comment.objects.create(visitor=visitor,email=email,content=content,date_time=date_time,restaurant=r)
            visitor,email,content=('','','')
'''

restaurants/templates/comments.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Comments</title>
    # bootstrap -----
    <link rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
    <link rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">
    <style>
        th { text-align: center; }
        div.comments {
            text-align: center;
            padding: 40px 15px;
        }


    </style>
    # ---------------
</head>
<body>
    # bootstrap -----
    <nav class="navbar navbar-inverse navbar-fixed-top"
         role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button"
                        class="navbar-toggle collapsed"
                        data-toggle="collapse"
                        data-target="#navbar"
                        aria-expanded="false"
                        aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="'icon-bar"></span>
                    <span class="'icon-bar"></span>
                    <span class="'icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Mysite</a>
            </div>
        </div>
    </nav>
    # ---------------
    <div class="container">
        <div class="comments">
            <h2>{{ r.name }}的評價</h2>
            {% if r.comment_set.all %}
                <p>目前共有 {{ r.comment_set.all|length }}條評價</p>
                <table class="table">
                    <tr>
                        <th>留言者</th>
                        <th>時間</th>
                        <th>評價</th>
                    </tr>
                    {% for c in r.comment_set.all %}
                        <tr>
                            <td>{{ c.visitor }}</td>
                            <td>{{ c.date_time | date:"F j, Y" }}</td>
                            <td>{{ c.content }}</td>
                        </tr>
                    {% endfor %}
                </table>
            {% else %}
                <p>無評價</p>
            {% endif %}

 <!--
            {% for e in errors %}
                <p style="color:red;">{{ e }}</p>
            {% endfor %}
 -->
            {% if f.errors %}
                <p style="color:red;">請修正</p>
            {% endif %}
        </div>
    </div>

    <form action="." method="post"> {% csrf_token %}
        <div class="comments">
        <table class="table">
            <tr>
                <th><label for="id_visitor">留言者：</label></th>
                <td>{{ f.visitor }}</td>
                <td>{{ f.visitor.errors }}</td>
            </tr>
            <tr>
                <th><label for="id_email">電子信箱：</label></th>
                <td>{{ f.email }}</td>
                <td>{{ f.email.errors }}</td>
            </tr>
            <tr>
                <th><label for="id_content">評價：</label></th>
                <td>{{ f.content }}</td>
                <td>{{ f.content.errors }}</td>
            </tr>
            <!--
            {{ f.as_table }}
            -->
            <!--
            <tr>
                <td><label for="visitor">留言者：</label></td>
                <td><input id="visitor" type="text" name="visitor" value="{{ visitor }}"></td>
            </tr>
            <tr>
                <td><label for="email">電子信箱：</label></td>
                <td><input id="email" type="text" name="email" value="{{ email }}"></td>
            </tr>
            <tr>
                <td><label for="content">評價：</label></td>
                <td><textarea id="content" rows="10" cols="48" name="content">{{ content }}</textarea></td>
            </tr>
            -->
        </table>
        <input type="submit" value="給予評價">
        </div>
    </form>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
</body>
</html>

restaurants/templates/menu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Menu</title>
    # bootstrap -----
    <link rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
    <link rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">
    <style>
        th { text-align: center; }
        div.menus {
            text-align: center;
            padding: 40px 15px;
        }
    </style>
    # ---------------
</head>
<body>
{% load myfilters %}
    # bootstrap -----
    <nav class="navbar navbar-inverse navbar-fixed-top"
         role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button"
                        class="navbar-toggle collapsed"
                        data-toggle="collapse"
                        data-target="#navbar"
                        aria-expanded="false"
                        aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="'icon-bar"></span>
                    <span class="'icon-bar"></span>
                    <span class="'icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Mysite</a>
            </div>
        </div>
    </nav>
    # ---------------
    <div class="container">
        <div class="menus">
        <p> 您現在的位置在 {{ path }}</p>
            <h2>{{ restaurant.name }}的 Menu</h2>
            {% if restaurant.food_set.all %}
                <p>本餐廳共有 {{ restaurant.food_set.all|length }}道菜</p>
                <table class="table">
                    <tr>
                        <th>菜名</th>
                        <th>價格</th>
                        <th>辣不辣</th>
                        <th>註解</th>
                    </tr>
                    {% for food in restaurant.food_set.all %}
                        <tr>
                            <td>{{ food.name }}</td>
                            <td>{{ food.price }}</td>
                            <!--
                            <td>{% if food.is_spicy %} 辣 {% else %}不辣
                                {% endif %}</td>
                            -->

                            <td>{{ food.is_spicy|yes_no:"辣/不辣" }}</td>
                            <td>{{ food.comment }}</td>
                        </tr>
                    {% endfor %}
                </table>
            {% else %}
                <p>賣完了</p>
            {% endif %}
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
</body>
</html>

restaurants/templates/restaurants_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Restaurants</title>
    # bootstrap -----
    <link rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
    <link rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">
    <style>
        th { text-align: center; }
        div.restaurants {
            text-align: center;
            padding: 40px 15px;
        }
    </style>
    # ---------------
</head>
{% load staticfiles %}
<body>
    # bootstrap -----
    <nav class="navbar navbar-inverse navbar-fixed-top"
         role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button"
                        class="navbar-toggle collapsed"
                        data-toggle="collapse"
                        data-target="#navbar"
                        aria-expanded="false"
                        aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="'icon-bar"></span>
                    <span class="'icon-bar"></span>
                    <span class="'icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Mysite</a>
            </div>
        </div>
    </nav>
    # ---------------
    <div class="container">
        <div class="restaurants">
            <h2>餐廳列表</h2>

        <p><img src="{% static 'img/logo.jpg' %}"></p>
            <!--方法23不要此行--> <form action="/menu/" method="get">
                <table class="table">
                    <tr>
                        <th>選取</th>
                        <th>店名</th>
                        <th>電話</th>
                        <th>地址</th>
                        {% if perms.restaurants.can_comment %}
                        <th>評價</th>
                        {% endif %}
                    </tr>
                    {% for r in restaurants %}
                        <tr>
                            <!--方法1 <td><input type="radio" name="id" value="{{ r.id }}"></td> -->
                            <!--方法2  <td><a href="/menu/?id={{ r.id }}"> 菜單 </a></td> -->
                            <!--方法3-->  <td><a href="/menu/{{ r.id }}/"> 菜單 </a></td>
                            <td>{{ r.name }}</td>
                            <td>{{ r.phone_number }}</td>
                            <td>{{ r.address }}</td>
                            {% if perms.restaurants.can_comment %}
                            <td><a href="/comment/{{ r.id }}"> 評論 </a></td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </table>
            <input type="submit" value="觀看 menu">
            </form>
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
</body>
</html>